#docker-compose.yaml for run app and mysqldb

version: '3.1'
services:
  web:
    restart: on-failure
    command: ["flask", "run", "--host=0.0.0.0"]
    build: .
    image: colonha/nexusapiservice
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - init-db
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

# mongodb
  mongo:
    image: mongo:latest    
    ports:
      - "27017:27017"
    volumes:
      - ../../data/db:/data/db
# init-db
  init-db:
    restart: on-failure
    command: ["python", "init_db.py"]
    build: .
    image: colonha/nexusapiservice
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase