apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexusapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexusapi
  template:
    metadata:
      labels:
        app: nexusapi
    spec:
      initContainers:
      - name: init-db
        image: colonha/nexusapiservice:latest
        command: ["python", "init_db.py"]
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: mongodb_url
      containers:
      - name: nexusapi
        image: colonha/nexusapiservice:latest
        command: ["flask", "run", "--host=0.0.0.0"]
        ports:
        - containerPort: 5000  # Flask default port
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: mongodb_url

