#docker-compose.yaml for run app and mysqldb

version: '3.1'
services:
  web:
    restart: on-failure
    command: ["flask", "run", "--host=0.0.0.0"]
    build: .
    image: colonha/nexusapiservice
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - init-db
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

# mongodb
  mongo:
    image: mongo:latest    
    ports:
      - "27017:27017"
    volumes:
      - ../../data:/data
# init-db
  init-db:
    restart: on-failure
    command: ["python", "app/init_db.py"]
    build: .
    image: colonha/nexusapiservice
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
# prometheus
  prometheus:
    image: prom/prometheus
    volumes:
      - ../infra/iac/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web
# grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3101:3000"
    volumes:
      - ../infra/iac/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../infra/iac/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../infra/iac/grafana/provisioning/dashboards/default.json:/var/lib/grafana/dashboards/default/default.json
    depends_on:
      - prometheus
